// Code generated by mockery v2.43.2. DO NOT EDIT.

package streamers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStreamer is an autogenerated mock type for the Streamer type
type MockStreamer struct {
	mock.Mock
}

type MockStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamer) EXPECT() *MockStreamer_Expecter {
	return &MockStreamer_Expecter{mock: &_m.Mock}
}

// PutRecord provides a mock function with given fields: ctx, data
func (_m *MockStreamer) PutRecord(ctx context.Context, data []byte) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for PutRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStreamer_PutRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRecord'
type MockStreamer_PutRecord_Call struct {
	*mock.Call
}

// PutRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockStreamer_Expecter) PutRecord(ctx interface{}, data interface{}) *MockStreamer_PutRecord_Call {
	return &MockStreamer_PutRecord_Call{Call: _e.mock.On("PutRecord", ctx, data)}
}

func (_c *MockStreamer_PutRecord_Call) Run(run func(ctx context.Context, data []byte)) *MockStreamer_PutRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockStreamer_PutRecord_Call) Return(_a0 error) *MockStreamer_PutRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamer_PutRecord_Call) RunAndReturn(run func(context.Context, []byte) error) *MockStreamer_PutRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStreamer creates a new instance of MockStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamer {
	mock := &MockStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
